#!/usr/bin/env python3
"""Bundles web/index.html (with web/pico_style.css and web/mask_core.js inlined) into src/web_index.h (C string constant for the daemon).

Usage (from the repo root):  python scripts/gen_web.py
The style (pico_style.css) and the mask drawing function (mask_core.js) come from the PicoAudio-Broadcast project (same look and same spectrum encoding).
"""
import os

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
rd = lambda p: open(os.path.join(root, p), encoding='utf-8', newline='').read().replace('\r\n', '\n')
html = rd('web/index.html').replace('/*@@CSS@@*/', rd('web/pico_style.css')).replace('/*@@MASKJS@@*/', rd('web/mask_core.js'))
data = html.encode('utf-8')

lines = ['// GENERATED by scripts/gen_web.py from web/index.html - do not edit by hand',
         'static const char WEB_INDEX[] =']
chunk = []
for ln in html.split('\n'):
    esc = ln.replace('\\', '\\\\').replace('"', '\\"')
    chunk.append('"' + esc + '\\n"')
lines.append('\n'.join(chunk) + ';')
lines.append('static const unsigned WEB_INDEX_LEN = sizeof(WEB_INDEX) - 1;')
open(os.path.join(root, 'src', 'web_index.h'), 'w', encoding='utf-8', newline='\n').write('\n'.join(lines) + '\n')
print('web_index.h: %d bytes HTML' % len(data))
