#!/usr/bin/env python3
"""Generates the coefficient functions of hdl/library/skypluto_wfm/skypluto_chanfilt.v (between the GENERATED markers) and the bit-exact
reference model used by sim/tb_chanfilt.v.

The channel filter band-limits the FM signal itself (after the modulator) so that the skirts at 110-170 kHz from the carrier, which set the
SM.1268 mask margin, are cut. Multirate, so it fits the FPGA:
    3.072 MS/s  --decimate x4, 32 taps-->  768 kS/s  --channel FIR, 63 taps-->  768 kS/s  --interpolate x4, 32 taps-->  3.072 MS/s
Three channel filters, -6 dB at +-130 / +-125 / +-120 kHz (Kaiser beta 8). Coefficients 18 bit signed, CB fraction bits.

    python scripts/gen_chanfilt.py            rewrite the coefficient functions in the Verilog
    python scripts/gen_chanfilt.py --model    also print the model's self-check
"""
import os, re, sys
import numpy as np
from scipy.signal import firwin

FS, FSD = 3072000, 768000
ND, NC, NI = 32, 63, 32
CB = 16
BWS = (130, 125, 120)

def q(h): return np.round(np.asarray(h) * 2**CB).astype(np.int64)

HD = q(firwin(ND, 384e3, fs=FS, window=('kaiser', 7.0)))                 # decimator, DC gain 1
HI = q(firwin(NI, 384e3, fs=FS, window=('kaiser', 7.0)) * 4)             # interpolator, gain 4 (zero stuffing)
HC = {bw: q(firwin(NC, bw * 1e3, fs=FSD, window=('kaiser', 8.0))) for bw in BWS}

def sat(v, bits):
    lo, hi = -(1 << (bits - 1)), (1 << (bits - 1)) - 1
    return np.clip(v, lo, hi)

def model(x, mode, ph=0):
    """bit-exact model. x = int16 samples at 3.072 MS/s; mode 1/2/3 = 130/125/120 kHz. Returns int16 at 3.072 MS/s.
    ph = which input sample is the newest one of a decimation frame (0..3)."""
    x = np.asarray(x, np.int64); hc = HC[BWS[mode - 1]]
    n_out = (len(x) - ph) // 4
    d = np.zeros(n_out, np.int64)
    for m in range(n_out):
        L = 4 * m + ph
        acc = 0
        for k in range(ND):
            if L - k >= 0: acc += HD[k] * x[L - k]
        d[m] = sat(acc >> CB, 18)
    c = np.zeros(n_out, np.int64)
    for m in range(n_out):
        acc = 0
        for k in range(NC):
            if m - k >= 0: acc += hc[k] * d[m - k]
        c[m] = sat(acc >> CB, 18)
    y = np.zeros(4 * n_out, np.int64)
    for m in range(n_out):
        for p in range(4):
            acc = 0
            for t in range(NI // 4):
                if m - t >= 0: acc += HI[4 * t + p] * c[m - t]
            y[4 * m + p] = sat(acc >> CB, 16)
    return y

def vfunc(name, coefs, half):
    n = len(coefs) // 2 + (1 if half == 'odd' else 0) if half else len(coefs)
    lines = ['    function signed [17:0] %s(input integer k);' % name, '        case (k)']
    for k in range(n):
        lines.append('            %d: %s = %d;' % (k, name, int(coefs[k])))
    lines += ['            default: %s = 0;' % name, '        endcase', '    endfunction']
    return lines

def generate():
    for h in [HD, HI] + list(HC.values()):
        assert np.abs(h).max() < (1 << 17), 'coefficient does not fit 18 bit'
        assert np.array_equal(h, h[::-1]) or h is HI, 'not symmetric'
    out = ['    // ---- GENERATED by scripts/gen_chanfilt.py - do not edit by hand ----']
    out += vfunc('c_dec', HD, 'even')                                       # 16 unique (symmetric, even length)
    out += vfunc('c_int', HI, None)                                         # 32 (polyphase: all of them)
    for i, bw in enumerate(BWS):
        out += vfunc('c_ch%d' % (i + 1), HC[bw], 'odd')                     # 32 unique (31 pairs + centre)
    out.append('    // ---- END GENERATED ----')
    p = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'hdl', 'library', 'skypluto_wfm', 'skypluto_chanfilt.v')
    s = open(p, encoding='utf-8').read()
    s = re.sub(r'    // ---- GENERATED.*?// ---- END GENERATED ----', '\n'.join(out), s, flags=re.S)
    open(p, 'w', encoding='utf-8', newline='\n').write(s)
    print('coefficients written to', os.path.normpath(p))

if __name__ == '__main__':
    generate()
